data = [
    {
        'id': 1,
        'age': 'youth',
        'income': 'high',
        'student': 'no',
        'credit_rating': 'fair',
        'buys_computer': 'no',
    },
    {
        'id': 2,
        'age': 'youth',
        'income': 'high',
        'student': 'no',
        'credit_rating': 'excellent',
        'buys_computer': 'no',
    },
    {
        'id': 3,
        'age': 'youth',
        'income': 'high',
        'student': 'no',
        'credit_rating': 'fair',
        'buys_computer': 'yes',
    },
    {
        'id': 4,
        'age': 'senior',
        'income': 'medium',
        'student': 'no',
        'credit_rating': 'fair',
        'buys_computer': 'yes',
    },
    {
        'id': 5,
        'age': 'senior',
        'income': 'high',
        'student': 'yes',
        'credit_rating': 'fair',
        'buys_computer': 'yes',
    },
    {
        'id': 6,
        'age': 'senior',
        'income': 'high',
        'student': 'yes',
        'credit_rating': 'excellent',
        'buys_computer': 'no',
    },
    {
        'id': 7,
        'age': 'youth',
        'income': 'high',
        'student': 'yes',
        'credit_rating': 'excellent',
        'buys_computer': 'yes',
    },
    {
        'id': 8,
        'age': 'youth',
        'income': 'medium',
        'student': 'no',
        'credit_rating': 'fair',
        'buys_computer': 'no',
    },
    {
        'id': 9,
        'age': 'youth',
        'income': 'high',
        'student': 'yes',
        'credit_rating': 'fair',
        'buys_computer': 'yes',
    },
    {
        'id': 10,
        'age': 'senior',
        'income': 'medium',
        'student': 'yes',
        'credit_rating': 'fair',
        'buys_computer': 'yes',
    },
    {
        'id': 11,
        'age': 'youth',
        'income': 'medium',
        'student': 'yes',
        'credit_rating': 'excellent',
        'buys_computer': 'yes',
    },
    {
        'id': 12,
        'age': 'youth',
        'income': 'medium',
        'student': 'no',
        'credit_rating': 'excellent',
        'buys_computer': 'yes',
    },
    {
        'id': 13,
        'age': 'youth',
        'income': 'high',
        'student': 'yes',
        'credit_rating': 'fair',
        'buys_computer': 'yes',
    },
    {
        'id': 14,
        'age': 'senior',
        'income': 'medium',
        'student': 'no',
        'credit_rating': 'excellent',
        'buys_computer': 'no',
    },
]